language: c

compiler:
  - gcc
  - clang

notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#o11c"
    on_success: always
    on_failure: always
    use_notice: true

script:
  - make
