language: c

dist: trusty

compiler:
  - gcc
  - clang

notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#o11c"
    on_success: always
    on_failure: always
    use_notice: true

install:
  - sudo apt-get install python3 python3-cffi
script:
  - make CC=$CC
