language: c

compiler:
  - gcc
  - clang

notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#o11c"
    on_success: always
    on_failure: always
    use_notice: true

install:
  - export PATH=$HOME/.local/bin:$PATH
  - sudo apt-get install python3
  - wget https://bootstrap.pypa.io/get-pip.py
  - python3 get-pip.py --user
  - pip3 install --user cffi
script:
  - make CC=$CC
